name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [mian]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-webapp ./webapp

      - name: Test container starts
        run: |
          docker run -d --name test-app my-webapp
          sleep 3
          docker logs test-app
          docker stop test-app

      - name: Confirm success
        run: echo "Pipeline passed - image builds and run correctly"
